import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync, rmSync } from "fs";
import { createHash } from "crypto";
import { join, relative, dirname, basename } from "path";
import { homedir } from "os";
import { GLOBAL_CONFIG_DIR } from "./config.js";

export interface ParsedRule {
  filePath: string;
  relativePath: string;
  frontmatter: {
    description?: string;
    globs?: string;
    alwaysApply?: boolean;
  };
  content: string;
}

export interface SyncResult {
  generated: string[];
  skipped: string[];
  errors: string[];
}

const CODEX_MAX_BYTES = 78000; // 80KB configured in ~/.codex/config.toml, leave headroom

function parseMdcFile(filePath: string): ParsedRule | null {
  const raw = readFileSync(filePath, "utf-8");
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);

  if (!match) {
    return {
      filePath,
      relativePath: "",
      frontmatter: {},
      content: raw,
    };
  }

  const [, frontmatterRaw, content] = match;
  const frontmatter: ParsedRule["frontmatter"] = {};

  for (const line of frontmatterRaw.split("\n")) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, value] = kv;
    if (key === "description") {
      frontmatter.description = value.replace(/^["']|["']$/g, "");
    } else if (key === "globs") {
      frontmatter.globs = value.trim() || undefined;
    } else if (key === "alwaysApply") {
      frontmatter.alwaysApply = value.trim() === "true";
    }
  }

  return {
    filePath,
    relativePath: "",
    frontmatter,
    content: content.trimStart(),
  };
}

function scanMdcFiles(rulesDir: string): ParsedRule[] {
  const rules: ParsedRule[] = [];

  function walk(dir: string) {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      const stat = statSync(full);
      if (stat.isDirectory()) {
        walk(full);
      } else if (entry.endsWith(".mdc") || entry.endsWith(".md")) {
        const parsed = parseMdcFile(full);
        if (parsed) {
          parsed.relativePath = relative(rulesDir, full);
          rules.push(parsed);
        }
      }
    }
  }

  walk(rulesDir);
  return rules;
}

function mdcToClaudeRule(rule: ParsedRule): string {
  const hasGlobs = rule.frontmatter.globs && rule.frontmatter.globs.trim().length > 0;

  if (hasGlobs) {
    const paths = rule.frontmatter.globs!
      .split(",")
      .map((g) => g.trim())
      .filter(Boolean);
    const pathsYaml = paths.map((p) => `  - "${p}"`).join("\n");
    return `---\npaths:\n${pathsYaml}\n---\n\n${rule.content}`;
  }

  // alwaysApply or no metadata → unconditional in Claude (no frontmatter)
  return rule.content;
}

function ensureDir(dir: string) {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
}

function ensureGitignore(workspace: string) {
  const gitignorePath = join(workspace, ".gitignore");
  const entries = [".claude/", "AGENTS.override.md", ".agents-override-hash"];

  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, entries.join("\n") + "\n");
    return;
  }

  const content = readFileSync(gitignorePath, "utf-8");
  const linesToAdd = entries.filter((e) => !content.includes(e));

  if (linesToAdd.length > 0) {
    const suffix = content.endsWith("\n") ? "" : "\n";
    const block = `${suffix}\n# Generated by thronglets rules sync\n${linesToAdd.join("\n")}\n`;
    writeFileSync(gitignorePath, content + block);
  }
}

export function syncForClaudeCode(workspace: string): SyncResult {
  const result: SyncResult = { generated: [], skipped: [], errors: [] };
  const cursorRulesDir = join(workspace, ".cursor", "rules");
  const agentsMdPath = join(workspace, "AGENTS.md");
  const claudeDir = join(workspace, ".claude");
  const claudeRulesDir = join(claudeDir, "rules");

  if (!existsSync(cursorRulesDir)) {
    result.errors.push(`No .cursor/rules/ directory found in ${workspace}`);
    return result;
  }

  // Clean previous generated rules
  if (existsSync(claudeRulesDir)) {
    rmSync(claudeRulesDir, { recursive: true, force: true });
  }
  ensureDir(claudeRulesDir);

  // Ensure .gitignore covers generated files
  ensureGitignore(workspace);

  // Generate .claude/CLAUDE.md from AGENTS.md
  if (existsSync(agentsMdPath)) {
    const agentsContent = readFileSync(agentsMdPath, "utf-8");
    writeFileSync(join(claudeDir, "CLAUDE.md"), agentsContent);
    result.generated.push(".claude/CLAUDE.md");
  } else {
    result.skipped.push("AGENTS.md (not found, skipping CLAUDE.md generation)");
  }

  // Scan and transform rules
  const rules = scanMdcFiles(cursorRulesDir);

  for (const rule of rules) {
    try {
      const claudeContent = mdcToClaudeRule(rule);

      // Preserve directory structure, change extension to .md
      const targetRelPath = rule.relativePath.replace(/\.mdc$/, ".md");
      const targetPath = join(claudeRulesDir, targetRelPath);

      ensureDir(dirname(targetPath));
      writeFileSync(targetPath, claudeContent);
      result.generated.push(`.claude/rules/${targetRelPath}`);
    } catch (err) {
      result.errors.push(`Failed to transform ${rule.relativePath}: ${(err as Error).message}`);
    }
  }

  return result;
}

function computeRulesHash(workspace: string): string {
  const hash = createHash("sha256");
  const cursorRulesDir = join(workspace, ".cursor", "rules");
  const agentsMdPath = join(workspace, "AGENTS.md");

  if (existsSync(agentsMdPath)) {
    hash.update(readFileSync(agentsMdPath));
  }

  if (existsSync(cursorRulesDir)) {
    const rules = scanMdcFiles(cursorRulesDir);
    for (const r of rules.sort((a, b) => a.relativePath.localeCompare(b.relativePath))) {
      hash.update(r.relativePath);
      hash.update(readFileSync(r.filePath));
    }
  }

  return hash.digest("hex").slice(0, 16);
}

function getOpenAIKey(): string | null {
  const configPath = join(GLOBAL_CONFIG_DIR, "config.yaml");
  if (existsSync(configPath)) {
    const content = readFileSync(configPath, "utf-8");
    const match = content.match(/api_key:\s*["']?(sk-proj-[^"'\s]+)/);
    if (match) return match[1];
  }
  // Fallback to env
  return process.env.OPENAI_API_KEY || null;
}

async function compressRulesWithLLM(
  fullContent: string,
  targetBytes: number,
): Promise<string> {
  const apiKey = getOpenAIKey();
  if (!apiKey) {
    throw new Error("No OpenAI API key found for compression");
  }

  const targetChars = Math.floor(targetBytes * 0.95); // leave margin
  const ratio = (targetChars / fullContent.length * 100).toFixed(0);

  const response = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: "gpt-4.1-mini",
      messages: [
        {
          role: "system",
          content: `You are a technical documentation compressor. Your job is to condense agent instructions to fit within a byte limit while preserving ALL actionable information (API endpoints, URLs, auth headers, parameters, tool names). 

Rules:
- Keep ALL API endpoints, URLs, and auth patterns EXACTLY as-is
- Keep ALL tool/command names
- Remove verbose explanations, keep terse descriptions
- Collapse tables into compact format
- Remove examples if the pattern is clear from the description
- Use abbreviations where unambiguous
- Target output: ~${ratio}% of input length (under ${targetChars} characters)
- Output pure markdown, no meta-commentary`,
        },
        {
          role: "user",
          content: `Compress this agent instruction document from ${fullContent.length} chars to under ${targetChars} chars. Preserve all API endpoints, tool names, and auth patterns:\n\n${fullContent}`,
        },
      ],
      max_tokens: Math.min(16000, Math.ceil(targetChars / 3)),
      temperature: 0.1,
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`OpenAI API error ${response.status}: ${err.slice(0, 200)}`);
  }

  const data = await response.json() as { choices: Array<{ message: { content: string } }> };
  return data.choices[0].message.content;
}

export async function syncForCodex(workspace: string): Promise<SyncResult> {
  const result: SyncResult = { generated: [], skipped: [], errors: [] };
  const cursorRulesDir = join(workspace, ".cursor", "rules");
  const agentsMdPath = join(workspace, "AGENTS.md");
  const overridePath = join(workspace, "AGENTS.override.md");
  const hashPath = join(workspace, ".agents-override-hash");

  if (!existsSync(agentsMdPath)) {
    result.errors.push("No AGENTS.md found — Codex needs this file");
    return result;
  }

  if (!existsSync(cursorRulesDir)) {
    result.skipped.push("No .cursor/rules/ — AGENTS.md alone is sufficient for Codex");
    return result;
  }

  // Check hash cache — skip LLM compression if rules haven't changed
  const currentHash = computeRulesHash(workspace);
  if (existsSync(overridePath) && existsSync(hashPath)) {
    const cachedHash = readFileSync(hashPath, "utf-8").trim();
    if (cachedHash === currentHash) {
      const size = Buffer.byteLength(readFileSync(overridePath), "utf-8");
      result.skipped.push(`AGENTS.override.md is up-to-date (${size} bytes, hash=${currentHash})`);
      return result;
    }
  }

  const rules = scanMdcFiles(cursorRulesDir);
  const alwaysApplyRules = rules.filter((r) => r.frontmatter.alwaysApply);

  const agentsContent = readFileSync(agentsMdPath, "utf-8");

  // Build full content: AGENTS.md + all alwaysApply rules
  const extraRules = alwaysApplyRules
    .filter((r) => !agentsContent.includes(r.content.slice(0, 100)))
    .map((r) => `\n\n---\n\n## ${r.frontmatter.description || basename(r.filePath, ".mdc")}\n\n${r.content}`);

  if (extraRules.length === 0) {
    result.skipped.push("All alwaysApply rules already covered in AGENTS.md");
    return result;
  }

  const fullContent = agentsContent + extraRules.join("");
  const fullSize = Buffer.byteLength(fullContent, "utf-8");

  if (fullSize <= CODEX_MAX_BYTES) {
    // Fits without compression
    writeFileSync(overridePath, fullContent);
    writeFileSync(hashPath, currentHash);
    result.generated.push(`AGENTS.override.md (${fullSize} bytes, no compression needed)`);
    return result;
  }

  // Needs compression via LLM
  console.log(`  [compress] Full content: ${fullSize} bytes, target: ${CODEX_MAX_BYTES} bytes`);
  console.log(`  [compress] Calling OpenAI gpt-4.1-mini to compress...`);

  try {
    const compressed = await compressRulesWithLLM(fullContent, CODEX_MAX_BYTES);
    const compressedSize = Buffer.byteLength(compressed, "utf-8");

    if (compressedSize > CODEX_MAX_BYTES) {
      const truncated = compressed.slice(0, CODEX_MAX_BYTES);
      writeFileSync(overridePath, truncated);
      writeFileSync(hashPath, currentHash);
      result.generated.push(
        `AGENTS.override.md (${compressedSize}→${CODEX_MAX_BYTES} bytes, compressed+truncated)`
      );
    } else {
      writeFileSync(overridePath, compressed);
      writeFileSync(hashPath, currentHash);
      result.generated.push(
        `AGENTS.override.md (${fullSize}→${compressedSize} bytes, LLM compressed)`
      );
    }
  } catch (err) {
    result.errors.push(`LLM compression failed: ${(err as Error).message}`);
    const truncated = fullContent.slice(0, CODEX_MAX_BYTES);
    writeFileSync(overridePath, truncated);
    writeFileSync(hashPath, currentHash);
    result.generated.push(`AGENTS.override.md (hard-truncated to ${CODEX_MAX_BYTES} bytes)`);
  }

  return result;
}

export type SyncTarget = "claude-code" | "codex" | "all";

export async function syncRules(workspace: string, target: SyncTarget = "all"): Promise<Record<string, SyncResult>> {
  const results: Record<string, SyncResult> = {};

  if (target === "claude-code" || target === "all") {
    results["claude-code"] = syncForClaudeCode(workspace);
  }

  if (target === "codex" || target === "all") {
    results["codex"] = await syncForCodex(workspace);
  }

  return results;
}

export function printSyncResults(results: Record<string, SyncResult>) {
  for (const [runtime, result] of Object.entries(results)) {
    console.log(`\n[rules-sync] ${runtime}:`);
    if (result.generated.length) {
      console.log(`  Generated (${result.generated.length}):`);
      for (const f of result.generated) console.log(`    + ${f}`);
    }
    if (result.skipped.length) {
      console.log(`  Skipped:`);
      for (const s of result.skipped) console.log(`    - ${s}`);
    }
    if (result.errors.length) {
      console.log(`  Errors:`);
      for (const e of result.errors) console.log(`    ! ${e}`);
    }
  }
}

export function getRulesStatus(workspace: string): {
  cursorRules: number;
  claudeRules: number;
  agentsMd: boolean;
  claudeMd: boolean;
  codexOverride: boolean;
  inSync: boolean;
} {
  const cursorRulesDir = join(workspace, ".cursor", "rules");
  const claudeRulesDir = join(workspace, ".claude", "rules");

  let cursorCount = 0;
  let claudeCount = 0;

  if (existsSync(cursorRulesDir)) {
    cursorCount = scanMdcFiles(cursorRulesDir).length;
  }

  if (existsSync(claudeRulesDir)) {
    claudeCount = scanMdcFiles(claudeRulesDir).length;
  }

  return {
    cursorRules: cursorCount,
    claudeRules: claudeCount,
    agentsMd: existsSync(join(workspace, "AGENTS.md")),
    claudeMd: existsSync(join(workspace, ".claude", "CLAUDE.md")),
    codexOverride: existsSync(join(workspace, "AGENTS.override.md")),
    inSync: cursorCount === claudeCount && cursorCount > 0,
  };
}
